import { Github } from 'lucide-react';

import { Button } from './components/ui/button';
import { Separator } from './components/ui/separator';
import { Textarea } from './components/ui/textarea';

export function App() {
  return (
    <div className="flex min-h-screen flex-col">
      <header className="flex items-center justify-between border-b px-6 py-3">
        <h1 className="text-xl font-bold">upload.ai</h1>

        <div className="flex items-center gap-3">
          <span className="text-sm text-muted-foreground">
            Desenvolvido com ❤ por Gabriel Bonizário
          </span>

          <Separator orientation="vertical" className="h-6" />

          <Button variant="outline">
            <Github className="mr-2 h-4 w-4" />
            GitHub
          </Button>
        </div>
      </header>

      <main className="flex flex-1 gap-6 p-6">
        <div className="flex flex-1 flex-col gap-4">
          <div className="grid flex-1 grid-rows-2 gap-4">
            <Textarea
              className="resize-none p-4 leading-relaxed"
              placeholder="Add the AI prompt..."
            />

            <Textarea
              className="resize-none p-4 leading-relaxed"
              placeholder="Output generated by AI..."
            />
          </div>

          <p className="text-sm text-muted-foreground">
            Don&apos;t forget, you have the option to incorporate the transcript content of the
            chosen video by using a{' '}
            <code className="text-secondary-foreground">&#123;transcription&#125;</code> variable in
            your prompt.
          </p>
        </div>

        <aside className="w-80">Aside</aside>
      </main>
    </div>
  );
}
